### ISSUE TITLE
A couple of feature requests

### ISSUE THREAD

**Issue by lmburns** [glepnir/nerdicons.nvim#2]
1. Choose the register that the icon is copied to
2. Choose the size of the popup window
3. A keybinding to reset the search without having to close the window
4. Allow `NerdIcons` to take an optional parameter which would start the search before the popup opens
5. A keybinding to move a page up/down at a time

Editing to add:
6. Allow searching by a glob/regex type pattern

If I have some time today, I'll try and implement some of these as well.

**Comment by glepnir** [comment]
1.  use `0` register is fine i think.
2. now you can config the width in options
3. idk what does this mean. press `<CR>` to search then it will clean the search keyword in prompt buffer you don't need close window
4. support you can use NerdIcons keyword
5. no need just move down move up is enough?
6. you can use the lua regex as keyword
